"""init

Revision ID: 8737665e852a
Revises: 
Create Date: 2026-09-28 22:19:44.776530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8737665e852a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('recipe_default_private', sa.Boolean(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gcb_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ingredients', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['gcb_users.id'], name=op.f('fk_gcb_recipes_user_id_gcb_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gcb_user_blocking',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blocking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blocking_id'], ['gcb_users.id'], name=op.f('fk_gcb_user_blocking_blocking_id_gcb_users')),
    sa.ForeignKeyConstraint(['user_id'], ['gcb_users.id'], name=op.f('fk_gcb_user_blocking_user_id_gcb_users')),
    sa.PrimaryKeyConstraint('user_id', 'blocking_id')
    )
    op.create_table('gcb_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['gcb_recipes.id'], name=op.f('fk_gcb_comments_recipe_id_gcb_recipes')),
    sa.ForeignKeyConstraint(['user_id'], ['gcb_users.id'], name=op.f('fk_gcb_comments_user_id_gcb_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gcb_favorite_recipes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['gcb_recipes.id'], name=op.f('fk_gcb_favorite_recipes_recipe_id_gcb_recipes')),
    sa.ForeignKeyConstraint(['user_id'], ['gcb_users.id'], name=op.f('fk_gcb_favorite_recipes_user_id_gcb_users')),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gcb_favorite_recipes')
    op.drop_table('gcb_comments')
    op.drop_table('gcb_user_blocking')
    op.drop_table('gcb_recipes')
    op.drop_table('gcb_users')
    # ### end Alembic commands ###
